<h1>Eliminazione Gaussiana</h1>

$$\begin{eqnarray}
L_1 \quad\quad & a_{11}x_1 & + & a_{12}x_2 & + & a_{13}x_3 & + & ... & + & a_{1n}x_n & \quad = & \quad b_1\\
L_2 \quad\quad & a_{21}x_1 & + & a_{22}x_2 & + & a_{23}x_3 & + & ... & + & a_{2n}x_n & \quad = & \quad b_2\\
L_3 \quad\quad & a_{31}x_1 & + & a_{32}x_2 & + & a_{33}x_3 & + & ... & + & a_{3n}x_n & \quad = & \quad b_3\\
    \quad\quad &    ...    &   &    ...    &   &    ...    &   & ... &   &    ...    & \quad   & \quad ...\\
L_n \quad\quad & a_{n1}x_1 & + & a_{n2}x_2 & + & a_{n3}x_3 & + & ... & + & a_{nn}x_n & \quad = & \quad b_n
\end{eqnarray}$$

<b>Step 1:</b> eliminare tutti gli $x_1$ tranne il primo.

Dobbiamo trovare un $m$ tale che:

\begin{equation}
    L_i - L_1 \cdot m = 0
\end{equation}

È fácile verificare che, se $m = \frac{a_{i1}}{a_{11}}$

\begin{equation}
    L_i - L_1 \cdot \frac{a_{i1}}{a_{11}} \quad = \quad a_{i1}x_1 - a_{11} \frac{a_{i1}}{a_{11}} \quad = \quad 0
\end{equation}

Il nuovo sistema di equazioni diventa:

$$\begin{eqnarray}
a_{11}x_1 & + & a_{12} x_2 & + & a_{13} x_3 & + & ... & + & a_{1n} x_n & \quad = & \quad b_1'\\
  \quad   & + & a_{22}'x_2 & + & a_{23}'x_3 & + & ... & + & a_{2n}'x_n & \quad = & \quad b_2'\\
  \quad   & + & a_{32}'x_2 & + & a_{33}'x_3 & + & ... & + & a_{3n}'x_n & \quad = & \quad b_3'\\
  \quad   &   &    ...     &   &    ...     &   & ... &   &    ...     & \quad   & \quad ...\\
  \quad   & + & a_{n2}'x_2 & + & a_{n3}'x_3 & + & ... & + & a_{nn}'x_n & \quad = & \quad b_n'
\end{eqnarray}$$

In forma matriciale:

\begin{equation*}
\begin{vmatrix}
a_{11} & + & a_{12}  & + & a_{13}  & + & ... & + & a_{1n}  \\
0      & + & a_{22}' & + & a_{23}' & + & ... & + & a_{2n}' \\
0      & + & a_{32}' & + & a_{33}' & + & ... & + & a_{3n}' \\
       &   &    ...  &   &    ...  &   & ... &   &    ...  \\
0      & + & a_{n2}' & + & a_{n3}' & + & ... & + & a_{nn}' 
\end{vmatrix}
\begin{vmatrix}
x_1 \\ x_2 \\ x_3 \\ ... \\ x_n
\end{vmatrix} 
\quad = \quad
\begin{vmatrix}
b_1' \\ b_2' \\ b_3' \\ ... \\ b_n'
\end{vmatrix}
\end{equation*}

Dove i coefficienti modificati sono dati da:

\begin{align}
    a_{ij}' \quad = \quad a_{ij} - a_{1j} \frac{a_{i1}}{a_{11}} & \quad\quad & b_i' \quad = \quad b_i - b_1 \frac{a_{i1}}{a_{11}}
\end{align}

<b>Esempio:</b>

$$\begin{eqnarray}
       x_1 & - 2 &x_2 & +   &x_3 & \quad = & \quad  &0\\
    \quad  & + 2 &x_2 & - 8 &x_3 & \quad = & \quad  &8\\
    -4 x_1 & + 5 &x_2 & + 9 &x_3 & \quad = & \quad -&9\\
\end{eqnarray}$$

\begin{equation*}
\begin{vmatrix}
    & 1&  &-2&  & 1& \\
    & 0&  & 2&  &-8& \\
    &-4&  & 5&  & 9& \\
\end{vmatrix}
\begin{vmatrix}
&x_1& \\ &x_2& \\ &x_3&
\end{vmatrix} 
\quad = \quad
\begin{vmatrix}
    & 0& \\ & 8& \\ &-9&
\end{vmatrix}
\end{equation*}

Matrice aumentata:

\begin{equation*}
\begin{vmatrix}
    & 1&  &-2&  & 1& & 0&\\
    & 0&  & 2&  &-8& & 8&\\
    &-4&  & 5&  & 9& &-9&\\
\end{vmatrix}
\end{equation*}

In [41]:
import numpy as np

In [61]:
A = np.array([[1.0, -2.0, 1.0, 0.0], [0.0, 2.0, -8.0, 8.0], [-4.0, 5.0, 9.0, -9.0]])
A

array([[ 1., -2.,  1.,  0.],
       [ 0.,  2., -8.,  8.],
       [-4.,  5.,  9., -9.]])

In [62]:
num_rows, num_cols = A.shape
M = A[:,0].copy()
M

array([ 1.,  0., -4.])

In [63]:
N = num_rows
for i in range(1,N):
        M[i] = A[i,0]/A[0,0]

In [64]:
for i in range(1,N):
    A[i] = A[i] - M[i]*A[0]

In [65]:
A

array([[ 1., -2.,  1.,  0.],
       [ 0.,  2., -8.,  8.],
       [ 0., -3., 13., -9.]])

In [66]:
M = A[:,1].copy()
M

array([-2.,  2., -3.])

In [67]:
for i in range(2,N):
        M[i] = A[i,1]/A[1,1]

In [68]:
M

array([-2. ,  2. , -1.5])

In [69]:
for i in range(2,N):
    A[i] = A[i] - M[i]*A[1]

In [70]:
A

array([[ 1., -2.,  1.,  0.],
       [ 0.,  2., -8.,  8.],
       [ 0.,  0.,  1.,  3.]])

Back substitution

In [79]:
x_3 = A[N-1,-1] / A[N-1,-2]
x_3

3.0